project "LithTech"
	kind "WindowedApp"
	language "C++"
	cppdialect "C++14"
	staticruntime "on"

	characterset ("MBCS")

	pchheader "bdefs.h"
	pchsource "%{rundir}/shared/src/bdefs.cpp"

	targetdir (bindir)
	objdir (intdir .. "/%{prj.name}")

	libdirs { bindir.. "/**" }

	defines { "DE_LOCAL_SERVERBIND", "DE_CLIENT_COMPILE", "DSNDMGR_NO_MFC", "DIRECTENGINE_COMPILE", "__D3D", "__D3DREND", "MODEL_SUPPORT_ABC", "D3D_DEBUG_INFO" }

	files
	{
		-- for future additions to the project itself
		"src/**.h",
		"src/**.cpp",
		"src/**.c",
		"src/*.rc",

		-- lib, sdk and runtime headers
		libdir .. "/LIB-RezMgr/src/rezfile.h",
		libdir .. "/LIB-RezMgr/src/rezhash.h",
		libdir .. "/LIB-RezMgr/src/rezmgr.h",
		libdir .. "/LIB-RezMgr/src/reztypes.h",
		sdkdir .. "/cui.h",
		sdkdir .. "/cuifont.h",
		sdkdir .. "/cuiformattedpolystring.h",
		sdkdir .. "/cuimessage.h",
		sdkdir .. "/cuipolystring.h",
		sdkdir .. "/cuitypes.h",
		sdkdir .. "/iaggregate.h",
		sdkdir .. "/iclientshell.h",
		sdkdir .. "/iltbaseclass.h",
		sdkdir .. "/iltbenchmark.h",
		sdkdir .. "/iltclient.h",
		sdkdir .. "/iltcommon.h",
		sdkdir .. "/iltcsbase.h",
		sdkdir .. "/iltcursor.h",
		sdkdir .. "/iltdirectmusic.h",
		sdkdir .. "/iltdrawprim.h",
		sdkdir .. "/iltfontmanager.h",
		sdkdir .. "/iltinfo.h",
		sdkdir .. "/iltmemory.h",
		sdkdir .. "/iltmessage.h",
		sdkdir .. "/iltmodel.h",
		sdkdir .. "/iltphysics.h",
		sdkdir .. "/iltrefcount.h",
		sdkdir .. "/iltrenderstyles.h",
		sdkdir .. "/iltserver.h",
		sdkdir .. "/iltsoundmgr.h",
		sdkdir .. "/iltspritecontrol.h",
		sdkdir .. "/iltstream.h",
		sdkdir .. "/ilttexinterface.h",
		sdkdir .. "/ilttexturestring.h",
		sdkdir .. "/ilttransform.h",
		sdkdir .. "/iltvideomgr.h",
		sdkdir .. "/iltwidgetmanager.h",
		sdkdir .. "/iservershell.h",
		sdkdir .. "/lithtech.h",
		sdkdir .. "/ltanimtracker.h",
		sdkdir .. "/ltassert.h",
		sdkdir .. "/ltbasedefs.h",
		sdkdir .. "/ltbasetypes.h",
		sdkdir .. "/ltcodes.h",
		sdkdir .. "/ltengineobjects.h",
		sdkdir .. "/lterror.h",
		sdkdir .. "/ltinteger.h",
		sdkdir .. "/ltlink.h",
		sdkdir .. "/ltmatrix.h",
		sdkdir .. "/ltmodule.h",
		sdkdir .. "/ltobjectcreate.h",
		sdkdir .. "/ltplane.h",
		sdkdir .. "/ltproperty.h",
		sdkdir .. "/ltpvalue.h",
		sdkdir .. "/ltquatbase.h",
		sdkdir .. "/ltrect.h",
		sdkdir .. "/ltrenderstyle.h",
		sdkdir .. "/ltrotation.h",
		sdkdir .. "/ltserverobj.h",
		sdkdir .. "/ltvector.h",
		sdkdir .. "/physics/aabb_tree.h",
		sdkdir .. "/physics/aabb.h",
		sdkdir .. "/physics/collision_data.h",
		sdkdir .. "/physics/collision_mgr.h",
		sdkdir .. "/physics/collision_object.h",
		sdkdir .. "/physics/coordinate_frame.h",
		sdkdir .. "/physics/math_phys.h",
		sdkdir .. "/physics/matrix.h",
		sdkdir .. "/physics/quaternion.h",
		sdkdir .. "/physics/rigid_body.h",
		sdkdir .. "/physics/triangle.h",
		sdkdir .. "/physics/vector.h",
		sdkdir .. "/server_interface.h",
		rundir .. "/client/src/client_filemgr.h",
		rundir .. "/client/src/client_formatmgr.h",
		rundir .. "/client/src/client_graphmgr.h",
		rundir .. "/client/src/client_ticks.h",
		rundir .. "/client/src/clientde_impl.h",
		rundir .. "/client/src/clientexception.h",
		rundir .. "/client/src/clientmgr.h",
		rundir .. "/client/src/clientshell.h",
		rundir .. "/client/src/cmoveabstract.h",
		rundir .. "/client/src/console.h",
		rundir .. "/client/src/consolecommands.h",
		rundir .. "/client/src/customfontfilemgr.h",
		rundir .. "/client/src/debuggraphmgr.h",
		rundir .. "/client/src/errorlog.h",
		rundir .. "/client/src/linesystem.h",
		rundir .. "/client/src/ltbenchmark_impl.h",
		rundir .. "/client/src/ltinfo_impl.h",
		rundir .. "/client/src/ltmessage_client.h",
		rundir .. "/client/src/lttexturestring.h",
		rundir .. "/client/src/memorywatch.h",
		rundir .. "/client/src/particlesystem.h",
		rundir .. "/client/src/polygrid.h",
		rundir .. "/client/src/predict.h",
		rundir .. "/client/src/setupobject.h",
		rundir .. "/client/src/sprite.h",
		rundir .. "/client/src/sys/win/winclientde_impl.h",
		rundir .. "/client/src/sys/win/winconsole_impl.h",
		rundir .. "/client/src/sysclient.h",
		rundir .. "/client/src/sysclientde_impl.h",
		rundir .. "/client/src/sysconsole_impl.h",
		rundir .. "/client/src/texturestring.h",
		rundir .. "/client/src/texturestringimage.h",
		rundir .. "/client/src/volumeeffect.h",
		rundir .. "/client/src/watermark.h",
		rundir .. "/controlfilemgr/controlfilemgr.h",
		rundir .. "/kernel/io/src/sys/win/de_file.h",
		rundir .. "/kernel/io/src/sysfile.h",
		rundir .. "/kernel/mem/src/de_memory.h",
		rundir .. "/kernel/net/src/localdriver.h",
		rundir .. "/kernel/net/src/netmgr.h",
		rundir .. "/kernel/net/src/packet.h",
		rundir .. "/kernel/net/src/sys/win/socket.h",
		rundir .. "/kernel/src/dsys.h",
		rundir .. "/kernel/src/icommandlineargs.h",
		rundir .. "/kernel/src/ithread.h",
		rundir .. "/kernel/src/sys/win/appresource.h",
		rundir .. "/kernel/src/sys/win/bindmgr.h",
		rundir .. "/kernel/src/sys/win/bink.h",
		rundir .. "/kernel/src/sys/win/binkvideomgrimpl.h",
		rundir .. "/kernel/src/sys/win/counter.h",
		rundir .. "/kernel/src/sys/win/dshowvideomgrimpl.h",
		rundir .. "/kernel/src/sys/win/dsys_interface.h",
		rundir .. "/kernel/src/sys/win/dutil.h",
		rundir .. "/kernel/src/sys/win/input.h",
		rundir .. "/kernel/src/sys/win/interface_helpers.h",
		rundir .. "/kernel/src/sys/win/load_pcx.h",
		rundir .. "/kernel/src/sys/win/ltdirectmusic_impl.h",
		rundir .. "/kernel/src/sys/win/ltdirectmusiccontrolfile.h",
		rundir .. "/kernel/src/sys/win/ltdirectmusicloader.h",
		rundir .. "/kernel/src/sys/win/lthread.h",
		rundir .. "/kernel/src/sys/win/ltrendermgr_impl.h",
		rundir .. "/kernel/src/sys/win/ltthread.h",
		rundir .. "/kernel/src/sys/win/musicdriver.h",
		rundir .. "/kernel/src/sys/win/rad.h",
		rundir .. "/kernel/src/sys/win/render.h",
		rundir .. "/kernel/src/sys/win/smack.h",
		rundir .. "/kernel/src/sys/win/streamsim.h",
		rundir .. "/kernel/src/sys/win/stringmgr.h",
		rundir .. "/kernel/src/sys/win/systeminfo.h",
		rundir .. "/kernel/src/sys/win/text_mgr.h",
		rundir .. "/kernel/src/sys/win/timemgr.h",
		rundir .. "/kernel/src/sys/win/version_resource.h",
		rundir .. "/kernel/src/sys/win/videomgr.h",
		rundir .. "/kernel/src/sys/win/winbind.h",
		rundir .. "/kernel/src/syscounter.h",
		rundir .. "/kernel/src/sysdebugging.h",
		rundir .. "/kernel/src/sysinput.h",
		rundir .. "/kernel/src/syslibraryloader.h",
		rundir .. "/kernel/src/sysstreamsim.h",
		rundir .. "/kernel/src/systhread.h",
		rundir .. "/kernel/src/systimer.h",
		rundir .. "/kernel/src/sysvideo.h",
		rundir .. "/lithtemplate/ltt_buffer.h",
		rundir .. "/lithtemplate/ltt_list_circular.h",
		rundir .. "/model/src/animtracker.h",
		rundir .. "/model/src/ltb.h",
		rundir .. "/model/src/model_ops.h",
		rundir .. "/model/src/model.h",
		rundir .. "/model/src/modelallocations.h",
		rundir .. "/model/src/transformmaker.h",
		rundir .. "/physics/src/lt_collision_mgr.h",
		rundir .. "/render_a/src/sys/d3d/clipline.h",
		rundir .. "/render_a/src/sys/d3d/common_draw.h",
		rundir .. "/render_a/src/sys/d3d/d3d_convar.h",
		rundir .. "/render_a/src/sys/d3d/d3d_device.h",
		rundir .. "/render_a/src/sys/d3d/d3d_draw.h",
		rundir .. "/render_a/src/sys/d3d/d3d_renderstatemgr.h",
		rundir .. "/render_a/src/sys/d3d/d3d_renderstyle.h",
		rundir .. "/render_a/src/sys/d3d/d3d_utils.h",
		rundir .. "/render_b/src/gendrawprim.h",
		rundir .. "/render_b/src/sys/d3d/d3ddrawprim.h",
		rundir .. "/render_b/src/sys/d3d/d3dtexinterface.h",
		rundir .. "/render_b/src/sysdrawprim.h",
		rundir .. "/server/src/classmgr.h",
		rundir .. "/server/src/game_serialize.h",
		rundir .. "/server/src/interlink.h",
		rundir .. "/server/src/ltmessage_server.h",
		rundir .. "/server/src/s_client.h",
		rundir .. "/server/src/s_concommand.h",
		rundir .. "/server/src/s_net.h",
		rundir .. "/server/src/s_object.h",
		rundir .. "/server/src/server_consolestate.h",
		rundir .. "/server/src/server_extradata.h",
		rundir .. "/server/src/server_filemgr.h",
		rundir .. "/server/src/serverde_impl.h",
		rundir .. "/server/src/serverevent.h",
		rundir .. "/server/src/serverexception.h",
		rundir .. "/server/src/servermgr.h",
		rundir .. "/server/src/serverobj.h",
		rundir .. "/server/src/smoveabstract.h",
		rundir .. "/server/src/soundtrack.h",
		rundir .. "/shared/src/bdefs.h",
		rundir .. "/shared/src/build_options.h",
		rundir .. "/shared/src/classbind.h",
		rundir .. "/shared/src/clienthack.h",
		rundir .. "/shared/src/collision.h",
		rundir .. "/shared/src/colorops.h",
		rundir .. "/shared/src/compress.h",
		rundir .. "/shared/src/concommand.h",
		rundir .. "/shared/src/conparse.h",
		rundir .. "/shared/src/DebugGeometry.h",
		rundir .. "/shared/src/dhashtable.h",
		rundir .. "/shared/src/dtxmgr.h",
		rundir .. "/shared/src/findobj.h",
		rundir .. "/shared/src/ftbase.h",
		rundir .. "/shared/src/ftclient.h",
		rundir .. "/shared/src/ftserv.h",
		rundir .. "/shared/src/gamemath.h",
		rundir .. "/shared/src/genericprop_setup.h",
		rundir .. "/shared/src/genltstream.h",
		rundir .. "/shared/src/geometry.h",
		rundir .. "/shared/src/geomroutines.h",
		rundir .. "/shared/src/impl_common.h",
		rundir .. "/shared/src/lightmap_compress.h",
		rundir .. "/shared/src/lightmap_planes.h",
		rundir .. "/shared/src/lightmapdefs.h",
		rundir .. "/shared/src/ltbbox.h",
		rundir .. "/shared/src/ltmessage.h",
		rundir .. "/shared/src/ltmutex.h",
		rundir .. "/shared/src/lttimer.h",
		rundir .. "/shared/src/misctools.h",
		rundir .. "/shared/src/motion.h",
		rundir .. "/shared/src/moveobject.h",
		rundir .. "/shared/src/moveplayer.h",
		rundir .. "/shared/src/musicmgr.h",
		rundir .. "/shared/src/nexus.h",
		rundir .. "/shared/src/objectmgr.h",
		rundir .. "/shared/src/packetdefs.h",
		rundir .. "/shared/src/parse_world_info.h",
		rundir .. "/shared/src/pixelformat.h",
		rundir .. "/shared/src/ratetracker.h",
		rundir .. "/shared/src/refobj.h",
		rundir .. "/shared/src/renderinfostruct.h",
		rundir .. "/shared/src/RenderObject.h",
		rundir .. "/shared/src/shared_iltcommon.h",
		rundir .. "/shared/src/stacktrace.h",
		rundir .. "/shared/src/staticfifo.h",
		rundir .. "/shared/src/stdlterror.h",
		rundir .. "/shared/src/strtools.h",
		rundir .. "/shared/src/sys/win/d3dddstructs.h",
		rundir .. "/shared/src/sys/win/dstreamopenqueuemgr.h",
		rundir .. "/shared/src/sys/win/renderstruct.h",
		rundir .. "/shared/src/sys/win/winstdlterror.h",
		rundir .. "/shared/src/sys/win/winsync.h",
		rundir .. "/shared/src/sysddstructs.h",
		rundir .. "/shared/src/varsetter.h",
		rundir .. "/shared/src/version_info.h",
		rundir .. "/sound/src/iltsound.h",
		rundir .. "/sound/src/soundbuffer.h",
		rundir .. "/sound/src/sounddata.h",
		rundir .. "/sound/src/soundinstance.h",
		rundir .. "/sound/src/soundmgr.h",
		rundir .. "/sound/src/wave.h",
		rundir .. "/ui/src/cuipolystring_impl.h",
		rundir .. "/world/src/de_mainworld.h",
		rundir .. "/world/src/de_objects.h",
		rundir .. "/world/src/de_sprite.h",
		rundir .. "/world/src/de_world.h",
		rundir .. "/world/src/fullintersectline.h",
		rundir .. "/world/src/intersect_line.h",
		rundir .. "/world/src/light_table.h",
		rundir .. "/world/src/loadstatus.h",
		rundir .. "/world/src/world_blind_object_data.h",
		rundir .. "/world/src/world_blocker_data.h",
		rundir .. "/world/src/world_blocker_math.h",
		rundir .. "/world/src/world_client_bsp.h",
		rundir .. "/world/src/world_client.h",
		rundir .. "/world/src/world_interface.h",
		rundir .. "/world/src/world_particle_blocker_data.h",
		rundir .. "/world/src/world_server_bsp.h",
		rundir .. "/world/src/world_server.h",
		rundir .. "/world/src/world_shared_bsp.h",
		rundir .. "/world/src/world_tree.h",
		rundir .. "/world/src/worldtreehelper.h",

		-- sdk and runtime sources
		sdkdir .. "/lterror.cpp",
		sdkdir .. "/ltmodule.cpp",
		sdkdir .. "/ltobjref.cpp",
		sdkdir .. "/ltquatbase.cpp",
		rundir .. "/client/src/client_filemgr.cpp",
		rundir .. "/client/src/client_formatmgr.cpp",
		rundir .. "/client/src/client_graphmgr.cpp",
		rundir .. "/client/src/client_iltcommon.cpp",
		rundir .. "/client/src/client_iltmodel.cpp",
		rundir .. "/client/src/client_iltphysics.cpp",
		rundir .. "/client/src/client_iltvideomgr.cpp",
		rundir .. "/client/src/client_ticks.cpp",
		rundir .. "/client/src/clientde_impl.cpp",
		rundir .. "/client/src/clientmgr.cpp",
		rundir .. "/client/src/clientshell.cpp",
		rundir .. "/client/src/cmoveabstract.cpp",
		rundir .. "/client/src/cnet.cpp",
		rundir .. "/client/src/cobject.cpp",
		rundir .. "/client/src/console.cpp",
		rundir .. "/client/src/consolecommands.cpp",
		rundir .. "/client/src/cutil.cpp",
		rundir .. "/client/src/debuggraphmgr.cpp",
		rundir .. "/client/src/errorlog.cpp",
		rundir .. "/client/src/linesystem.cpp",
		rundir .. "/client/src/ltbenchmark_impl.cpp",
		rundir .. "/client/src/ltinfo_impl.cpp",
		rundir .. "/client/src/ltmessage_client.cpp",
		rundir .. "/client/src/lttexturestring.cpp",
		rundir .. "/client/src/memorywatch.cpp",
		rundir .. "/client/src/particlesystem.cpp",
		rundir .. "/client/src/polygrid.cpp",
		rundir .. "/client/src/predict.cpp",
		rundir .. "/client/src/setupobject.cpp",
		rundir .. "/client/src/shellnet.cpp",
		rundir .. "/client/src/shelltransfer.cpp",
		rundir .. "/client/src/shellutil.cpp",
		rundir .. "/client/src/sprite.cpp",
		rundir .. "/client/src/sys/win/customfontfilemgr.cpp",
		rundir .. "/client/src/sys/win/texturestringimage.cpp",
		rundir .. "/client/src/sys/win/winclientde_impl.cpp",
		rundir .. "/client/src/sys/win/winconsole_impl.cpp",
		rundir .. "/client/src/texturestring.cpp",
		rundir .. "/client/src/volumeeffect.cpp",
		rundir .. "/client/src/watermark.cpp",
		rundir .. "/client/src/world_client_bsp.cpp",
		rundir .. "/controlfilemgr/controlfilemgr.cpp",
		rundir .. "/kernel/io/src/sys/win/de_file.cpp",
		rundir .. "/kernel/mem/src/ltmemory.cpp",
		rundir .. "/kernel/mem/src/sys/win/de_memory.cpp",
		rundir .. "/kernel/net/src/localdriver.cpp",
		rundir .. "/kernel/net/src/netmgr.cpp",
		rundir .. "/kernel/net/src/packet.cpp",
		rundir .. "/kernel/net/src/sys/win/udpdriver.cpp",
		rundir .. "/kernel/src/debugging.cpp",
		rundir .. "/kernel/src/icommandlineargs.cpp",
		rundir .. "/kernel/src/sys/win/bindmgr.cpp",
		rundir .. "/kernel/src/sys/win/binkvideomgrimpl.cpp",
		rundir .. "/kernel/src/sys/win/client.cpp",
		rundir .. "/kernel/src/sys/win/counter.cpp",
		rundir .. "/kernel/src/sys/win/dshowvideomgrimpl.cpp",
		rundir .. "/kernel/src/sys/win/dsys_interface.cpp",
		rundir .. "/kernel/src/sys/win/dutil.cpp",
		rundir .. "/kernel/src/sys/win/input.cpp",
		rundir .. "/kernel/src/sys/win/InputSim.cpp",
		rundir .. "/kernel/src/sys/win/interface_helpers.cpp",
		rundir .. "/kernel/src/sys/win/load_pcx.cpp",
		rundir .. "/kernel/src/sys/win/lt_cursor_impl.cpp",
		rundir .. "/kernel/src/sys/win/ltdirectmusic_impl.cpp",
		rundir .. "/kernel/src/sys/win/ltdirectmusiccontrolfile.cpp",
		rundir .. "/kernel/src/sys/win/ltdirectmusicloader.cpp",
		rundir .. "/kernel/src/sys/win/lthread.cpp",
		rundir .. "/kernel/src/sys/win/ltlibraryloader.cpp",
		rundir .. "/kernel/src/sys/win/ltrendermgr_impl.cpp",
		rundir .. "/kernel/src/sys/win/ltthread.cpp",
		rundir .. "/kernel/src/sys/win/musicdriver.cpp",
		rundir .. "/kernel/src/sys/win/render.cpp",
		rundir .. "/kernel/src/sys/win/streamsim.cpp",
		rundir .. "/kernel/src/sys/win/stringmgr.cpp",
		rundir .. "/kernel/src/sys/win/systeminfo.cpp",
		rundir .. "/kernel/src/sys/win/text_mgr.cpp",
		rundir .. "/kernel/src/sys/win/timemgr.cpp",
		rundir .. "/kernel/src/sys/win/version_resource.cpp",
		rundir .. "/kernel/src/sys/win/videomgr.cpp",
		rundir .. "/model/src/animtracker.cpp",
		rundir .. "/model/src/model_load.cpp",
		rundir .. "/model/src/model.cpp",
		rundir .. "/model/src/modelallocations.cpp",
		rundir .. "/model/src/sys/d3d/d3d_model_load.cpp",
		rundir .. "/model/src/sys/null/nullmodel_load.cpp",
		rundir .. "/model/src/transformmaker.cpp",
		rundir .. "/render_b/src/sys/d3d/d3ddrawprim.cpp",
		rundir .. "/render_b/src/sys/d3d/d3dtexinterface.cpp",
		rundir .. "/server/src/classmgr.cpp",
		rundir .. "/server/src/game_serialize.cpp",
		rundir .. "/server/src/interlink.cpp",
		rundir .. "/server/src/ltmessage_server.cpp",
		rundir .. "/server/src/s_client.cpp",
		rundir .. "/server/src/s_concommand.cpp",
		rundir .. "/server/src/S_Intersect.cpp",
		rundir .. "/server/src/s_net.cpp",
		rundir .. "/server/src/s_object.cpp",
		rundir .. "/server/src/server_consolestate.cpp",
		rundir .. "/server/src/server_extradata.cpp",
		rundir .. "/server/src/server_filemgr.cpp",
		rundir .. "/server/src/server_iltcommon.cpp",
		rundir .. "/server/src/server_iltmodel.cpp",
		rundir .. "/server/src/server_iltphysics.cpp",
		rundir .. "/server/src/server_iltsoundmgr.cpp",
		rundir .. "/server/src/serverde_impl.cpp",
		rundir .. "/server/src/serverevent.cpp",
		rundir .. "/server/src/servermgr.cpp",
		rundir .. "/server/src/smoveabstract.cpp",
		rundir .. "/server/src/soundtrack.cpp",
		rundir .. "/server/src/world_server_bsp.cpp",
		rundir .. "/shared/src/bdefs.cpp",
		rundir .. "/shared/src/classbind.cpp",
		rundir .. "/shared/src/collision.cpp",
		rundir .. "/shared/src/compress.cpp",
		rundir .. "/shared/src/concommand.cpp",
		rundir .. "/shared/src/conparse.cpp",
		rundir .. "/shared/src/debuggeometry.cpp",
		rundir .. "/shared/src/dhashtable.cpp",
		rundir .. "/shared/src/dtxmgr.cpp",
		rundir .. "/shared/src/engine_vars.cpp",
		rundir .. "/shared/src/findobj.cpp",
		rundir .. "/shared/src/ftclient.cpp",
		rundir .. "/shared/src/ftserv.cpp",
		rundir .. "/shared/src/gamemath.cpp",
		rundir .. "/shared/src/genericprop_setup.cpp",
		rundir .. "/shared/src/genltstream.cpp",
		rundir .. "/shared/src/geometry.cpp",
		rundir .. "/shared/src/geomroutines.cpp",
		rundir .. "/shared/src/impl_common.cpp",
		rundir .. "/shared/src/interface_linkage.cpp",
		rundir .. "/shared/src/leech.cpp",
		rundir .. "/shared/src/lightmap_compress.cpp",
		rundir .. "/shared/src/lightmap_planes.cpp",
		rundir .. "/shared/src/ltmessage.cpp",
		rundir .. "/shared/src/lttimer.cpp",
		rundir .. "/shared/src/modellt_impl.cpp",
		rundir .. "/shared/src/motion.cpp",
		rundir .. "/shared/src/moveobject.cpp",
		rundir .. "/shared/src/moveplayer.cpp",
		rundir .. "/shared/src/nexus.cpp",
		rundir .. "/shared/src/objectmgr.cpp",
		rundir .. "/shared/src/parse_world_info.cpp",
		rundir .. "/shared/src/pixelformat.cpp",
		rundir .. "/shared/src/ratetracker.cpp",
		rundir .. "/shared/src/shared_iltcommon.cpp",
		rundir .. "/shared/src/shared_iltphysics.cpp",
		rundir .. "/shared/src/spritecontrolimpl.cpp",
		rundir .. "/shared/src/stacktrace.cpp",
		rundir .. "/shared/src/stdlterror.cpp",
		rundir .. "/shared/src/strtools.cpp",
		rundir .. "/shared/src/sys/win/dstreamopenqueuemgr.cpp",
		rundir .. "/shared/src/transformlt_impl.cpp",
		rundir .. "/shared/src/version_info.cpp",
		rundir .. "/sound/src/soundbuffer.cpp",
		rundir .. "/sound/src/sounddata.cpp",
		rundir .. "/sound/src/soundinstance.cpp",
		rundir .. "/sound/src/soundmgr.cpp",
		rundir .. "/sound/src/wave.cpp",
		rundir .. "/world/src/de_mainworld.cpp",
		rundir .. "/world/src/de_nodes.cpp",
		rundir .. "/world/src/de_objects.cpp",
		rundir .. "/world/src/fullintersectline.cpp",
		rundir .. "/world/src/intersect_line.cpp",
		rundir .. "/world/src/intersectsweptsphere.cpp",
		rundir .. "/world/src/light_table.cpp",
		rundir .. "/world/src/world_blind_object_data.cpp",
		rundir .. "/world/src/world_blocker_data.cpp",
		rundir .. "/world/src/world_blocker_math.cpp",
		rundir .. "/world/src/world_particle_blocker_data.cpp",
		rundir .. "/world/src/world_shared_bsp.cpp",
		rundir .. "/world/src/world_tree.cpp"
	}

	removefiles { rundir .. "/model/src/sys/null/nullmodel_load.cpp" }

	includedirs
	{
		"src",

		-- sdk
		sdkdir,
		sdkdir .. "/physics",
		sdkdir .. "/state_mgr",

		-- runtime
		rundir,
		rundir .. "/client/src",
		rundir .. "/controlfilemgr",
		rundir .. "/kernel/src",
		rundir .. "/kernel/io/src",
		rundir .. "/kernel/mem/src",
		rundir .. "/kernel/net/src",
		rundir .. "/kernel/src/sys/win",
		rundir .. "/lithtemplate",
		rundir .. "/model/src",
		rundir .. "/physics/src",
		rundir .. "/render_a/src/sys/d3d",
		rundir .. "/render_b/src",
		rundir .. "/server/src",
		rundir .. "/shared/src",
		rundir .. "/shared/src/sys/win",
		rundir .. "/sound/src",
		rundir .. "/ui/src",
		rundir .. "/world/src",

		-- external libs
		libdir .. "/LIB-DShow/src",
		libdir .. "/LIB-Lith/src",
		libdir .. "/LIB-LTMem/src",
		libdir .. "/LIB-MFCStub/src",
		libdir .. "/LIB-RezMgr/src",
		libdir .. "/LIB-STDLith/src"
	}

	-- DX9 / DX8 includes
	externalincludedirs
	{
		"$(DXSDK_DIR)Include",
		vendir
	}

	-- DX9 / DX8 library
	syslibdirs
	{
		"$(DXSDK_DIR)Lib/x86",
		vendir .. "/directx-8.1/lib"
	}

	links
	{
		"ddraw",
		"d3d9",
		"d3dx9",
		"dxerr",
		"dxguid",
		"winmm",
		"atls",
		"dplayx",
		"dinput8",
		"odbc32",
		"odbccp32",

		"LIB-Info",
		"LIB-Render",
		"LIB-Sound",
		"LIB-UI",

		"LIB-DShow",
		"LIB-Lith",
		"LIB-LTMem",
		"LIB-MFCStub",
		"LIB-RezMgr",
		"LIB-STDLith"
	}

	-- we need to disable PCH for some files

	-- sdk
	filter { "files:**/sdk/inc/lterror.cpp" }
		flags "NoPCH"

	filter { "files:**/sdk/inc/ltmodule.cpp" }
		flags "NoPCH"

	filter { "files:**/sdk/inc/ltobjref.cpp" }
		flags "NoPCH"

	filter { "files:**/sdk/inc/ltquatbase.cpp" }
		flags "NoPCH"

	-- runtime-controlfilemgr
	filter { "files:**/runtime/controlfilemgr/controlfilemgr.cpp" }
		flags "NoPCH"

	-- runtime-client
	filter { "files:**/runtime/client/src/client_formatmgr.cpp" }
		flags "NoPCH"

	filter { "files:**/runtime/client/src/clientmgr.cpp" }
		flags "NoPCH"

	-- runtime-kernel
	filter { "files:**/runtime/kernel/src/icommandlineargs.cpp" }
		flags "NoPCH"

	filter { "files:**/runtime/shared/src/modellt_impl.cpp" }
		flags "NoPCH"

	filter { "files:**/runtime/kernel/src/sys/win/client.cpp" }
		flags "NoPCH"

	filter { "files:**/runtime/kernel/src/sys/win/counter.cpp" }
		flags "NoPCH"

	-- runtime-shared
	filter { "files:**/runtime/shared/src/compress.cpp" }
		flags "NoPCH"

	filter { "files:**/runtime/shared/src/interface_linkage.cpp" }
		flags "NoPCH"
